### ISSUE TITLE
bonus generated on map border

### ISSUE THREAD

**Issue by soliton-** [vgaming/bonus_tiles#1]
![bonustilebug](https://user-images.githubusercontent.com/3579817/217781450-0bd71f9e-ff4c-4f6e-a5a8-6075a5dfe1c4.png)

Map border tiles are used for bonuses but shouldn't because you can't collect them.

**Comment by vgaming** [comment]
Hi Gunter, thanks for the report! I *think* I've fixed it, although I'm not certain. To be honest, I don't have Wesnoth installed at the moment, so I've attempted a blind fix. I hope I didn't break anything, I think it shouldn't. Please report if anything is off (version 0.5.2. released just now)
